### ISSUE TITLE
Использование псевдоэлементов ::before, ::after

### ISSUE THREAD

**Issue by mprohorovevapps** [plutosshow/praktic2020#6]
В целом для таких элементов как подчёркивание в заголовках (.rectangle.bot-20) и квадраты рядом с изображениями (.square.team__square) лучше использовать псевдоэлементы, т. к. они используются исключительно с оформительскими целями и не несут никакой семантической нагрузки.
http://htmlbook.ru/css/before
Примерно так:
```css
.specialties__img {
    position: relative;
}

.specialties__img::before {
    content: '',
    width: 226px;
    height: 226px;
    display: block;
    position: absolute;
    left: - 50%;
    top: 25%;
    border: 20px solid #E8C300;
}
```
